const artists = 
['Lee "Scratch" Perry',
'Curtis Mayfield',
'Roxy Music',
'The Supremes',
'Martha and The Vandellas',
'Lynyrd Skynyrd',
'Nine Inch Nails',
'Booker T. & The M.G.',
'Guns n Roses',
'Rick Nelson',
'Carlos Santana',
'Yardbirds',
'Miles Davis',
'Gram Parsons',
'2Pac',
'Black Sabbath',
'James Taylor',
'N.W.A',
'Eminem',
"The Drifters",
'Elvis Costello',
'Four Tops',
'The Stooges',
'Beastie Boys',
'The Shirelles',
'Eagles',
'Hank Williams',
'Radiohead',
'AC/DC',
'Frank Zappa',
'The Police',
'Carl Perkins',
'Jackie Wilson',
'The Temptations',
'Cream',
'Al Green',
'The Kinks',
'Etta James',
'Tina Turner',
'Joni Mitchell',
'Louis Jordan',
'Sex Pistols',
'Aerosmith',
'Parliament',
'Grateful Dead',
'Dr. Dre',
'Eric Clapton',
'The Allman Brothers Band',
'Howlin Wolf',
'The Band',
'Elton John',
'Run-D.M.C.',
'Patti Smith',
'Janis Joplin',
'The Byrds',
'Public Enemy',
'Sly & The Family Stone',
'Van Morrison',
'The Doors',
'Simon & Garfunkel',
'David Bowie',
'John Lennon',
'Roy Orbison',
'Madonna',
'Michael Jackson',
'Neil Young',
'The Everly Brothers',
'The Miracles',
'Johnny Cash',
'The Clash',
'The Who',
'Prince',
'Nirvana',
'Ramones',
'Fats Domino',
'Jerry Lee Lewis',
'Bruce Springsteen',
'U2',
'Otis Redding',
'Bo Diddley',
'The Velvet Underground',
'Marvin Gaye',
'Muddy Waters',
'Sam Cooke',
'Stevie Wonder',
'Led Zeppelin',
'Buddy Holly',
'The Beach Boys',
'Bob Marley',
'Ray Charles',
'Aretha Franklin',
'Little Richard',
'James Brown',
'Jimi Hendrix',
'Chuck Berry',
'The Rolling Stones',
'Elvis Presley',
'Bob Dylan',
'The Beatles'];

export default artists  ;